version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_app
    command:
      -p 5432
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: mytbot_app
    command: ["/mytbot/docker/app.sh"]
    depends_on:
      - db