"""Добавил в таб medicine notifications

Revision ID: b22ea8e82020
Revises: b0c7ce38ca8f
Create Date: 2023-03-13 18:32:56.340176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22ea8e82020'
down_revision = 'b0c7ce38ca8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('notifications', sa.Boolean(), default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine', 'notifications')
    # ### end Alembic commands ###
